### ISSUE TITLE
Color entire blocks instead of just the first instruction

### ISSUE THREAD

**Issue by assafcarlsbad** [gamozolabs/mesos#5]
When coloring the graph in IDA, I think it would be better to color entire blocks rather than just the first instruction of each block. This will make the graph look something like this:
![image](https://user-images.githubusercontent.com/8438963/52722222-e2aab300-2fb3-11e9-996f-b3f8aee3c59e.png)

We can get the boundaries of each block using this small utility function:
```python
def addr2block(addr):
    f = idaapi.get_func(addr)
    if not f:
        print "No function at 0x%x" % (addr)
        return

    fc = idaapi.FlowChart(f)

    for block in fc:
        if (block.startEA <= addr) and (block.endEA > addr):
                return (block.startEA, block.endEA)
```

**Comment by gamozolabs** [comment]
I agree. Mesos originally put breakpoints on every PC and I never updated it. Technically coloring blocks might lead to coloring un-hit code (if there is a path that always crashes or something), but I think it's better to color the blocks. Merged in e331dd3560583500a50e8628d4d2b9b3b84feb59
